### PR TITLE
Fix duplicate "e" error.

### PR DESCRIPTION
**Pull request by HTMLGhozt**
Quick fix to fix duplicate 'e' error. Further considerations would be to change how that loop works to be more inline with how JS usually works. x-post in decoding Jamie?

## Description
Changed variable name

## Related Issue
Quick dirty and easy fix to #35 

## Context
#35

## How Has This Been Tested?
Built Create-react-app locally.

### CODE REVIEW

**Comment by datagutt** [comment]
Directly touching dist, oof.

**Comment by HTMLGhozt** [comment]
There's some related stuff to go with this. I also did mention it was quick and dirty.

- related: https://github.com/mishoo/UglifyJS/pull/521

**Comment by datagutt** [comment]
"#webpack 4.26.0 now uses terser as default minimizer. It's officially backward-compatible to uglify-js, but who knows... 🤔"
https://twitter.com/wsokra/status/1064441984532848641
But this would work for now anyhow.

**Comment by HTMLGhozt** [comment]
Good to know.

**Comment by jamiepine** [comment]
I can't merge this because your changes will be overwritten as pulse.min.js is automatically generated on every build by webpack, though I know you know this. Maybe I should merge the rollup branch and see if that fixes it... webpack is drunk.

**Pull request closed without merging**
